### PR TITLE
[WIP] (Work in progress)

### PR DESCRIPTION
**Pull request by chayakornwc**

### CODE REVIEW

**Comment by TomasHubelbauer** [comment]
Did you mean to open this up as a PR? Currently you are replacing the actual main README.md and CONTRIBUTING.md with a Thai edition. It seems better suited to be a separate file with an ISO code language suffix,

**Comment by ripzery** [comment]
@TomasHubelbauer I think he might want to contribute to this repo https://github.com/reactbkk/react-in-patterns-th/issues/11 which will translate the original book to Thai version, but he mistakenly opened PR in this repo. 😓

**Comment by krasimir** [comment]
@ripzery that makes sense. @chayakornwc is that the case?

**Comment by chayakornwc** [comment]
i'm sorry, just wrong  repo :(

**Pull request closed without merging**
